import { CountryData } from './store';

export const countries: CountryData[] = [
  { code: 'SA', name: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية', currency: 'SAR', currencySymbol: 'ر.س', flag: '🇸🇦' },
  { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', currency: 'AED', currencySymbol: 'د.إ', flag: '🇦🇪' },
  { code: 'US', name: 'United States', nameAr: 'الولايات المتحدة', currency: 'USD', currencySymbol: '$', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', nameAr: 'المملكة المتحدة', currency: 'GBP', currencySymbol: '£', flag: '🇬🇧' },
  { code: 'EG', name: 'Egypt', nameAr: 'مصر', currency: 'EGP', currencySymbol: 'ج.م', flag: '🇪🇬' },
  { code: 'PK', name: 'Pakistan', nameAr: 'باكستان', currency: 'PKR', currencySymbol: '₨', flag: '🇵🇰' },
  { code: 'IN', name: 'India', nameAr: 'الهند', currency: 'INR', currencySymbol: '₹', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', nameAr: 'إندونيسيا', currency: 'IDR', currencySymbol: 'Rp', flag: '🇮🇩' },
  { code: 'MY', name: 'Malaysia', nameAr: 'ماليزيا', currency: 'MYR', currencySymbol: 'RM', flag: '🇲🇾' },
  { code: 'TR', name: 'Turkey', nameAr: 'تركيا', currency: 'TRY', currencySymbol: '₺', flag: '🇹🇷' },
  { code: 'BD', name: 'Bangladesh', nameAr: 'بنغلاديش', currency: 'BDT', currencySymbol: '৳', flag: '🇧🇩' },
  { code: 'NG', name: 'Nigeria', nameAr: 'نيجيريا', currency: 'NGN', currencySymbol: '₦', flag: '🇳🇬' },
  { code: 'QA', name: 'Qatar', nameAr: 'قطر', currency: 'QAR', currencySymbol: 'ر.ق', flag: '🇶🇦' },
  { code: 'KW', name: 'Kuwait', nameAr: 'الكويت', currency: 'KWD', currencySymbol: 'د.ك', flag: '🇰🇼' },
  { code: 'BH', name: 'Bahrain', nameAr: 'البحرين', currency: 'BHD', currencySymbol: 'د.ب', flag: '🇧🇭' },
  { code: 'OM', name: 'Oman', nameAr: 'عُمان', currency: 'OMR', currencySymbol: 'ر.ع', flag: '🇴🇲' },
  { code: 'JO', name: 'Jordan', nameAr: 'الأردن', currency: 'JOD', currencySymbol: 'د.أ', flag: '🇯🇴' },
  { code: 'LB', name: 'Lebanon', nameAr: 'لبنان', currency: 'LBP', currencySymbol: 'ل.ل', flag: '🇱🇧' },
  { code: 'MA', name: 'Morocco', nameAr: 'المغرب', currency: 'MAD', currencySymbol: 'د.م', flag: '🇲🇦' },
  { code: 'DZ', name: 'Algeria', nameAr: 'الجزائر', currency: 'DZD', currencySymbol: 'د.ج', flag: '🇩🇿' },
  { code: 'TN', name: 'Tunisia', nameAr: 'تونس', currency: 'TND', currencySymbol: 'د.ت', flag: '🇹🇳' },
  { code: 'LY', name: 'Libya', nameAr: 'ليبيا', currency: 'LYD', currencySymbol: 'د.ل', flag: '🇱🇾' },
  { code: 'SD', name: 'Sudan', nameAr: 'السودان', currency: 'SDG', currencySymbol: 'ج.س', flag: '🇸🇩' },
  { code: 'IQ', name: 'Iraq', nameAr: 'العراق', currency: 'IQD', currencySymbol: 'ع.د', flag: '🇮🇶' },
  { code: 'SY', name: 'Syria', nameAr: 'سوريا', currency: 'SYP', currencySymbol: 'ل.س', flag: '🇸🇾' },
  { code: 'YE', name: 'Yemen', nameAr: 'اليمن', currency: 'YER', currencySymbol: 'ر.ي', flag: '🇾🇪' },
  { code: 'PS', name: 'Palestine', nameAr: 'فلسطين', currency: 'ILS', currencySymbol: '₪', flag: '🇵🇸' },
  { code: 'AF', name: 'Afghanistan', nameAr: 'أفغانستان', currency: 'AFN', currencySymbol: '؋', flag: '🇦🇫' },
  { code: 'IR', name: 'Iran', nameAr: 'إيران', currency: 'IRR', currencySymbol: '﷼', flag: '🇮🇷' },
  { code: 'CA', name: 'Canada', nameAr: 'كندا', currency: 'CAD', currencySymbol: '$', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', nameAr: 'أستراليا', currency: 'AUD', currencySymbol: '$', flag: '🇦🇺' },
  { code: 'DE', name: 'Germany', nameAr: 'ألمانيا', currency: 'EUR', currencySymbol: '€', flag: '🇩🇪' },
  { code: 'FR', name: 'France', nameAr: 'فرنسا', currency: 'EUR', currencySymbol: '€', flag: '🇫🇷' },
  { code: 'IT', name: 'Italy', nameAr: 'إيطاليا', currency: 'EUR', currencySymbol: '€', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', nameAr: 'إسبانيا', currency: 'EUR', currencySymbol: '€', flag: '🇪🇸' },
  { code: 'NL', name: 'Netherlands', nameAr: 'هولندا', currency: 'EUR', currencySymbol: '€', flag: '🇳🇱' },
  { code: 'BE', name: 'Belgium', nameAr: 'بلجيكا', currency: 'EUR', currencySymbol: '€', flag: '🇧🇪' },
  { code: 'SE', name: 'Sweden', nameAr: 'السويد', currency: 'SEK', currencySymbol: 'kr', flag: '🇸🇪' },
  { code: 'NO', name: 'Norway', nameAr: 'النرويج', currency: 'NOK', currencySymbol: 'kr', flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark', nameAr: 'الدنمارك', currency: 'DKK', currencySymbol: 'kr', flag: '🇩🇰' },
  { code: 'CH', name: 'Switzerland', nameAr: 'سويسرا', currency: 'CHF', currencySymbol: 'Fr', flag: '🇨🇭' },
  { code: 'AT', name: 'Austria', nameAr: 'النمسا', currency: 'EUR', currencySymbol: '€', flag: '🇦🇹' },
  { code: 'PL', name: 'Poland', nameAr: 'بولندا', currency: 'PLN', currencySymbol: 'zł', flag: '🇵🇱' },
  { code: 'RU', name: 'Russia', nameAr: 'روسيا', currency: 'RUB', currencySymbol: '₽', flag: '🇷🇺' },
  { code: 'UA', name: 'Ukraine', nameAr: 'أوكرانيا', currency: 'UAH', currencySymbol: '₴', flag: '🇺🇦' },
  { code: 'ZA', name: 'South Africa', nameAr: 'جنوب أفريقيا', currency: 'ZAR', currencySymbol: 'R', flag: '🇿🇦' },
  { code: 'KE', name: 'Kenya', nameAr: 'كينيا', currency: 'KES', currencySymbol: 'KSh', flag: '🇰🇪' },
  { code: 'GH', name: 'Ghana', nameAr: 'غانا', currency: 'GHS', currencySymbol: '₵', flag: '🇬🇭' },
  { code: 'SN', name: 'Senegal', nameAr: 'السنغال', currency: 'XOF', currencySymbol: 'CFA', flag: '🇸🇳' },
  { code: 'ML', name: 'Mali', nameAr: 'مالي', currency: 'XOF', currencySymbol: 'CFA', flag: '🇲🇱' },
  { code: 'NE', name: 'Niger', nameAr: 'النيجر', currency: 'XOF', currencySymbol: 'CFA', flag: '🇳🇪' },
  { code: 'BF', name: 'Burkina Faso', nameAr: 'بوركينا فاسو', currency: 'XOF', currencySymbol: 'CFA', flag: '🇧🇫' },
  { code: 'CI', name: 'Ivory Coast', nameAr: 'ساحل العاج', currency: 'XOF', currencySymbol: 'CFA', flag: '🇨🇮' },
  { code: 'GM', name: 'Gambia', nameAr: 'غامبيا', currency: 'GMD', currencySymbol: 'D', flag: '🇬🇲' },
  { code: 'SL', name: 'Sierra Leone', nameAr: 'سيراليون', currency: 'SLL', currencySymbol: 'Le', flag: '🇸🇱' },
  { code: 'TZ', name: 'Tanzania', nameAr: 'تنزانيا', currency: 'TZS', currencySymbol: 'TSh', flag: '🇹🇿' },
  { code: 'UG', name: 'Uganda', nameAr: 'أوغندا', currency: 'UGX', currencySymbol: 'USh', flag: '🇺🇬' },
  { code: 'SO', name: 'Somalia', nameAr: 'الصومال', currency: 'SOS', currencySymbol: 'Sh', flag: '🇸🇴' },
  { code: 'DJ', name: 'Djibouti', nameAr: 'جيبوتي', currency: 'DJF', currencySymbol: 'Fdj', flag: '🇩🇯' },
  { code: 'KM', name: 'Comoros', nameAr: 'جزر القمر', currency: 'KMF', currencySymbol: 'CF', flag: '🇰🇲' },
  { code: 'MV', name: 'Maldives', nameAr: 'المالديف', currency: 'MVR', currencySymbol: 'Rf', flag: '🇲🇻' },
  { code: 'BN', name: 'Brunei', nameAr: 'بروناي', currency: 'BND', currencySymbol: '$', flag: '🇧🇳' },
  { code: 'SG', name: 'Singapore', nameAr: 'سنغافورة', currency: 'SGD', currencySymbol: '$', flag: '🇸🇬' },
  { code: 'PH', name: 'Philippines', nameAr: 'الفلبين', currency: 'PHP', currencySymbol: '₱', flag: '🇵🇭' },
  { code: 'TH', name: 'Thailand', nameAr: 'تايلاند', currency: 'THB', currencySymbol: '฿', flag: '🇹🇭' },
  { code: 'JP', name: 'Japan', nameAr: 'اليابان', currency: 'JPY', currencySymbol: '¥', flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea', nameAr: 'كوريا الجنوبية', currency: 'KRW', currencySymbol: '₩', flag: '🇰🇷' },
  { code: 'CN', name: 'China', nameAr: 'الصين', currency: 'CNY', currencySymbol: '¥', flag: '🇨🇳' },
  { code: 'HK', name: 'Hong Kong', nameAr: 'هونغ كونغ', currency: 'HKD', currencySymbol: '$', flag: '🇭🇰' },
  { code: 'NZ', name: 'New Zealand', nameAr: 'نيوزيلندا', currency: 'NZD', currencySymbol: '$', flag: '🇳🇿' },
  { code: 'BR', name: 'Brazil', nameAr: 'البرازيل', currency: 'BRL', currencySymbol: 'R$', flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico', nameAr: 'المكسيك', currency: 'MXN', currencySymbol: '$', flag: '🇲🇽' },
  { code: 'AR', name: 'Argentina', nameAr: 'الأرجنتين', currency: 'ARS', currencySymbol: '$', flag: '🇦🇷' },
  { code: 'CL', name: 'Chile', nameAr: 'تشيلي', currency: 'CLP', currencySymbol: '$', flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia', nameAr: 'كولومبيا', currency: 'COP', currencySymbol: '$', flag: '🇨🇴' },
];

// Default gold prices by currency (approximate, should be updated)
export const defaultGoldPrices: Record<string, number> = {
  USD: 70,
  EUR: 65,
  GBP: 55,
  SAR: 263,
  AED: 257,
  EGP: 3500,
  PKR: 19500,
  INR: 5850,
  IDR: 1100000,
  MYR: 310,
  TRY: 2400,
  BDT: 7700,
  NGN: 115000,
  QAR: 255,
  KWD: 21,
  BHD: 26,
  OMR: 27,
  JOD: 50,
  MAD: 700,
  DZD: 9400,
  TND: 220,
  CAD: 95,
  AUD: 107,
  CHF: 62,
  JPY: 10500,
  CNY: 505,
  default: 70,
};

export function getGoldPriceForCurrency(currency: string): number {
  return defaultGoldPrices[currency] ?? defaultGoldPrices.default;
}
